---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Install PHP
  apt:
    name: php
    state: present

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present